version: "3.2"
services:
  harvester:
    build: harvester
    ports:
      - 8448:8448
    environment:
      TZ: "America/Denver"
      USER_ID: 1000
      GROUP_ID: 1000
    sysctls:
      net.ipv6.conf.lo.disable_ipv6: 0
    volumes:
      - /tub/chia/harvester:/chia/.chia
      - /chia/plots1:/chia-plots-1
      - /chia/plots2:/chia-plots-2
      - /chia/plots3:/chia-plots-3
    restart: unless-stopped

